checks:
    php: true

filter:
    paths:
        - "src/*"

tools:
    php_code_coverage:
        enabled: true

build:
    nodes:
        analysis:
            environment:
                php: 7.4.12

                variables:
                    COMPOSER_ROOT_VERSION: 'dev-master'

            tests:
                override:
                    - php-scrutinizer-run
