checks:
    php: true

filter:
    paths:
        - "src/*"

tools:
    external_code_coverage:
        timeout: 660

build:
    nodes:
        analysis:
            environment:
                php: 8.0.18

                variables:
                    COMPOSER_ROOT_VERSION: 'dev-master'

            tests:
                override:
                    - php-scrutinizer-run
