name: yiisoft-db
services:
  php:
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./../src:/code/src
      - ./../tests:/code/tests
      - ./../composer.json:/code/composer.json
      - ./../phpunit.xml.dist:/code/phpunit.xml.dist
    environment:
      YII_MYSQL_DATABASE: yii
      YII_MYSQL_HOST: mysql
      YII_MYSQL_PORT: 3306
      YII_MYSQL_USER: root
      YII_MYSQL_PASSWORD: root
      YII_MYSQL_TYPE: mysql

      YII_MARIADB_DATABASE: yii
      YII_MARIADB_HOST: mariadb
      YII_MARIADB_PORT: 13306
      YII_MARIADB_USER: root
      YII_MARIADB_PASSWORD: root

      YII_PGSQL_DATABASE: yii
      YII_PGSQL_HOST: postgres
      YII_PGSQL_PORT: 5432
      YII_PGSQL_USER: postgres
      YII_PGSQL_PASSWORD: postgres

      YII_MSSQL_DATABASE: tempdb
      YII_MSSQL_HOST: mssql
      YII_MSSQL_PORT: 1433
      YII_MSSQL_USER: SA
      YII_MSSQL_PASSWORD: YourStrong!Passw0rd

      YII_ORACLE_SID: FREE
      YII_ORACLE_DATABASE: FREEPDB1
      YII_ORACLE_HOST: oracle
      YII_ORACLE_PORT: 1521
      YII_ORACLE_USER: system
      YII_ORACLE_PASSWORD: sys_user_password

      ORACLE_PASSWORD: sys_user_password
      APP_USER: my_user
      APP_USER_PASSWORD: password_i_should_change
    command: tail -F anything
    depends_on:
      mysql:
        condition: service_healthy
      mariadb:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mssql:
        condition: service_healthy
      oracle:
        condition: service_healthy
  mysql:
    image: mysql:9
    ports:
      - "3306:3306"
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
    environment:
      MYSQL_DATABASE: yii
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot" ]
      interval: 5s
      timeout: 5s
      retries: 20
  mariadb:
    image: mariadb:11
    ports:
      - "13306:3306"
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
    environment:
      MYSQL_DATABASE: yii
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_TCP_PORT: 13306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 30
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: yii
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    user: root
    volumes:
      - mssql-data:/var/opt/mssql/data
      - mssql-log:/var/opt/mssql/log
      - mssql-secrets:/var/opt/mssql/secrets
    environment:
      SA_PASSWORD: YourStrong!Passw0rd
      ACCEPT_EULA: Y
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$${SA_PASSWORD}" -Q "SELECT 1" -b -C -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 100
      start_period: 10s
  oracle:
    build:
      context: oracle
    ports:
      - "1521:1521"
    volumes:
      - ./oracle/init.sql:/docker-entrypoint-initdb.d/init.sql
      - oracle-data:/opt/oracle/oradata
    environment:
      ORACLE_PASSWORD: sys_user_password
      APP_USER: my_user
      APP_USER_PASSWORD: password_i_should_change
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 100
      start_period: 5s
      start_interval: 5s
volumes:
  mssql-data:
  mssql-log:
  mssql-secrets:
  oracle-data:
