<?php

declare(strict_types=1);

namespace Yiisoft\Db\Cache;

use Yiisoft\Cache\CacheInterface;
use Yiisoft\Cache\CacheKeyNormalizer;
use Yiisoft\Cache\Dependency\Dependency;
use Yiisoft\Cache\Dependency\TagDependency;

/**
 * The cache application component that is used to cache the table metadata.
 */
final class SchemaCache
{
    private CacheInterface $cache;
    private bool $enabled = true;
    private int $duration = 3600;
    private array $exclude = [];
    private CacheKeyNormalizer $keyNormalizer;

    public function __construct(CacheInterface $cache, CacheKeyNormalizer $keyNormalizer)
    {
        $this->cache = $cache;
        $this->keyNormalizer = $keyNormalizer;
    }

    /**
     * Deletes a value with the specified key from cache.
     *
     * @param mixed $key a key identifying the value to be deleted from cache.
     *
     * @return bool if no error happens during deletion.
     */
    public function delete($key): bool
    {
        return $this->cache->delete($key);
    }

    /**
     * Normalizes cache key from a given key.
     *
     * If the given key is a string containing alphanumeric characters only and no more than 32 characters,
     * then the key will be returned back as it is, integers will be converted to strings. Otherwise,
     * a normalized key is generated by serializing the given key and applying MD5 hashing.
     *
     * @param mixed $key The key to be normalized.
     *
     * @return string The normalized cache key.
     */
    public function normalize($key): string
    {
        return $this->keyNormalizer->normalize($key);
    }

    public function get($key, $default = null)
    {
        return $this->cache->get($key, $default);
    }

    /**
     * Return number of seconds that table metadata can remain valid in cache.
     *
     * @return int
     */
    public function getDuration(): int
    {
        return $this->duration;
    }

    /**
     * Return true if the table is excluded from cache the table metadata.
     *
     * @return bool
     */
    public function isExcluded(string $value): bool
    {
        return in_array($value, $this->exclude, true);
    }

    /**
     * Invalidates all of the cached values that are associated with any of the specified {@see tags}.
     *
     * @param string $tags
     */
    public function invalidate(string $cacheTag): void
    {
        TagDependency::invalidate($this->cache, $cacheTag);
    }

    /**
     * Return true if SchemaCache is active.
     *
     * @return bool
     */
    public function isEnabled(): bool
    {
        return $this->enabled;
    }

    public function set($key, $value, $ttl = null, Dependency $dependency = null): bool
    {
        return $this->cache->set($key, $value, $ttl, $dependency);
    }

    /**
     * Whether to enable schema caching. Note that in order to enable truly schema caching, a valid cache component as
     * specified must be enabled and {@see setEnable()} must be set true.
     *
     * @param bool $value
     *
     * {@see setduration()}
     * {@see setExclude()}
     */
    public function setEnable(bool $value): void
    {
        $this->enabled = $value;
    }

    /**
     * Number of seconds that table metadata can remain valid in cache. Use 0 to indicate that the cached data will
     * never expire.
     *
     * @param int $value
     *
     * {@see setEnable()}
     */
    public function setDuration(int $value): void
    {
        $this->duration = $value;
    }

    /**
     * List of tables whose metadata should NOT be cached. Defaults to empty array. The table names may contain schema
     * prefix, if any. Do not quote the table names.
     *
     * @param array $value
     *
     * {@see setEnable()}
     */
    public function setExclude(array $value): void
    {
        $this->exclude = $value;
    }
}
