on:
  pull_request:
    paths: &paths
      - 'src/**'
      - '.github/workflows/bc.yml'
      - 'composer.json'
  push:
    branches: ['master']
    paths: *paths

name: backwards compatibility

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  roave_bc_check:
    uses: yiisoft/actions/.github/workflows/bc.yml@master
    with:
      php: >-
        ['8.5']
