name: changelog

on:
  pull_request:
    paths:
      - 'src/**'
      - 'config/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changelog:
    uses: yiisoft/actions/.github/workflows/changelog.yml@master
