on:
  pull_request:
    paths:
      - 'src/**'
      - 'config/**'
      - '.github/workflows/composer-require-checker.yml'
      - 'composer.json'
      - 'composer-require-checker.json'

  push:
    branches: ['master']
    paths:
      - 'src/**'
      - 'config/**'
      - '.github/workflows/composer-require-checker.yml'
      - 'composer.json'
      - 'composer-require-checker.json'

name: Composer require checker

jobs:
  composer-require-checker:
    uses: yiisoft/actions/.github/workflows/composer-require-checker.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.0', '8.1']
