on:
  pull_request:
    paths:
      - 'src/**'
      - 'config/**'
      - '.github/workflows/composer-require-checker.yml'
      - 'composer.json'
      - 'composer-require-checker.json'

  push:
    branches: ['master']
    paths:
      - 'src/**'
      - 'config/**'
      - '.github/workflows/composer-require-checker.yml'
      - 'composer.json'
      - 'composer-require-checker.json'

name: Composer require checker

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  composer-require-checker:
    uses: yiisoft/actions/.github/workflows/composer-require-checker.yml@master
    with:
      php: >-
        ['8.1', '8.2', '8.3', '8.4']
