name: mutation

on:
  pull_request:
    paths: &paths
      - 'src/**'
      - 'config/**'
      - 'tests/**'
      - '.github/workflows/mutation.yml'
      - 'composer.json'
      - 'phpunit.xml.dist'
      - 'infection.json.dist'

  push:
    branches: ['master']
    paths: *paths

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: yiisoft/actions/.github/workflows/db-mutation.yml@master
